name: Build Docker image and deploy to heroku
on:
  workflow_run:
    workflows: Lint and test
    branches: deployment
    types: completed
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker run -p 8088:8088 deepsea-dev/catvibestwo