name: Build Docker image and deploy to heroku
on:
  workflow_run:
    workflows: Lint and test
    branches: main
    types: completed
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build . -t deepsea-dev/catvibestwo
          docker save deepsea-dev/catvibestwo > build.tar
      - name: Cache
        uses: actions/cache@v3
        with:
          path: build.tar
          key: docker_file
  upload-artifact:
    name: Upload artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get image
        uses: actions/cache@v3
        with:
          path: build.tar
          key: docker_file
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: build.tar
        
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get image
        uses: actions/cache@v3
        with:
          path: build.tar
          key: docker_file
      - name: Login to Heroku
        run: docker login --username=${{ secrets.HEROKU_EMAIL }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
      - name: Publish image
        run: |
          docker load < build.tar
          docker tag deepsea-dev/catvibestwo registry.heroku.com/catvibestwo/web
          docker push registry.heroku.com/catvibestwo/web
      - name: Release
        run: heroku container:release web
