name: Build Docker image and deploy to heroku
on:
  workflow_run:
    workflows: Lint and test
    branches: main
    types: completed
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build . -t deepsea-dev/catvibestwo
          docker save deepsea-dev/catvibestwo > build.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: build.tar
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
